window.ads = [
{"id":1,"title":"هاتف ذكي بشاشة كبيرة","desc":"هاتف ذكي بشاشة 6.5 إنش وبطارية تدوم طوال اليوم.","image":"https://via.placeholder.com/800x450?text=Ad+1","link":"/p/ad1.html","category":"electronics","featured":true,"status":"active","expires":"2025-12-30","oldPrice":0,"newPrice":0,"currency":"$","tags":["electronics","tech","gold"],"badge":"gold"},
{"id":2,"title":"سماعات بلوتوث لاسلكية","desc":"سماعات عازلة للضوضاء بجودة صوت نقية.","image":"https://via.placeholder.com/800x450?text=Ad+2","link":"/p/ad2.html","category":"electronics","featured":true,"status":"active","expires":"2025-11-15","oldPrice":0,"newPrice":0,"currency":"$","tags":["electronics","tech","gold"],"badge":"gold"},
{"id":3,"title":"ساعة ذكية متعددة الوظائف","desc":"ساعة ذكية لمتابعة صحتك وإشعارات هاتفك.","image":"https://via.placeholder.com/800x450?text=Ad+3","link":"/p/ad3.html","category":"electronics","featured":false,"status":"active","expires":"2025-10-20","oldPrice":0,"newPrice":0,"currency":"$","tags":["electronics","tech","gold"],"badge":"gold"},
{"id":4,"title":"حاسوب محمول للأعمال","desc":"لابتوب خفيف الوزن بأداء قوي مناسب للأعمال.","image":"https://via.placeholder.com/800x450?text=Ad+4","link":"/p/ad4.html","category":"electronics","featured":true,"status":"active","expires":"2025-09-18","oldPrice":0,"newPrice":0,"currency":"$","tags":["electronics","tech","gold"],"badge":"gold"},
{"id":5,"title":"شاشة عرض عالية الدقة","desc":"شاشة 27 إنش بدقة عالية لتجربة مشاهدة مريحة.","image":"https://via.placeholder.com/800x450?text=Ad+5","link":"/p/ad5.html","category":"electronics","featured":false,"status":"active","expires":"2025-08-10","oldPrice":0,"newPrice":0,"currency":"$","tags":["electronics","tech","gold"],"badge":"gold"},

{"id":6,"title":"كاميرا رقمية احترافية","desc":"كاميرا بدقة عالية مناسبة للتصوير الاحترافي.","image":"https://via.placeholder.com/800x450?text=Ad+6","link":"/p/ad6.html","category":"electronics","featured":true,"status":"active","expires":"2025-07-22","oldPrice":0,"newPrice":0,"currency":"$","tags":["electronics","camera","gold"],"badge":"gold"},
{"id":7,"title":"لوحة مفاتيح ميكانيكية","desc":"لوحة مفاتيح بإضاءة RGB.","image":"https://via.placeholder.com/800x450?text=Ad+7","link":"/p/ad7.html","category":"electronics","featured":false,"status":"active","expires":"2025-06-18","oldPrice":0,"newPrice":0,"currency":"$","tags":["electronics","keyboard","gold"],"badge":"gold"},
{"id":8,"title":"ماوس ألعاب احترافي","desc":"ماوس دقة عالية لمحبي الألعاب.","image":"https://via.placeholder.com/800x450?text=Ad+8","link":"/p/ad8.html","category":"electronics","featured":true,"status":"active","expires":"2025-05-30","oldPrice":0,"newPrice":0,"currency":"$","tags":["electronics","gaming","gold"],"badge":"gold"},
{"id":9,"title":"سماعات رأس سلكية","desc":"سماعات بجودة صوت ممتازة.","image":"https://via.placeholder.com/800x450?text=Ad+9","link":"/p/ad9.html","category":"electronics","featured":false,"status":"active","expires":"2025-04-12","oldPrice":0,"newPrice":0,"currency":"$","tags":["electronics","audio","gold"],"badge":"gold"},
{"id":10,"title":"ميكروفون احترافي","desc":"ميكروفون بجودة عالية للبث والتسجيل.","image":"https://via.placeholder.com/800x450?text=Ad+10","link":"/p/ad10.html","category":"electronics","featured":true,"status":"active","expires":"2025-03-28","oldPrice":0,"newPrice":0,"currency":"$","tags":["electronics","audio","gold"],"badge":"gold"},

...  
(جميع الإعلانات من 1 إلى 100 كما هي تمامًا)  
...

{"id":100,"title":"قلم توقيع فاخر","desc":"قلم توقيع معدني فاخر بتصميم راقٍ.","image":"https://via.placeholder.com/800x450?text=Ad+100","link":"/p/ad100.html","category":"culture","featured":true,"status":"active","expires":"2025-06-10","oldPrice":0,"newPrice":0,"currency":"$","tags":["culture","luxury","gold"],"badge":"gold"}
];
